name: Deploy-Nest-PM2
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Clone project to EC2
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout the files
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: npm install

      - name: Gerando build
        run: npm run build

      - name: Executando os testes
        run: npm run test

      - name: Copy files with SSH
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: "./"
          REMOTE_HOST: "ec2-52-54-155-216.compute-1.amazonaws.com"
          REMOTE_USER: "ubuntu"
          TARGET: "/var/www/petguardian-api"
          EXCLUDE: "/dist/, /node_modules/, *.env, rebuild_app.sh, watcher.sh"

  build:
    name: SSH and deploy to EC2
    runs-on: ubuntu-latest
    needs: deploy

    steps:
      - uses: actions/checkout@v3
      - name: Build & Deploy
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOSTNAME: ec2-52-54-155-216.compute-1.amazonaws.com
          USERNAME: ubuntu
        
        run:
          echo "$PRIVATE_KEY" > private_key.pem && chmod 600 private_key.pem && eval "$(ssh-agent -s)" && ssh-add private_key.pem &&
          ssh -o StrictHostKeyChecking=no -i private_key.pem ${USERNAME}@${HOSTNAME} '
            export PATH=$PATH:/home/ubuntu/.nvm/versions/node/v20.6.1/bin &&
            cd /var/www/petguardian-api &&
            npm install &&
            npm run build &&
            pm2 restart pet-guardian_api
          '
      