name: Deploy-Nest-PM2
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Clone project to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v3

      - name: Copy files with SSH and start build
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: "./"
          REMOTE_HOST: "ec2-52-54-155-216.compute-1.amazonaws.com"
          REMOTE_USER: "ubuntu"
          TARGET: "/var/www/petguardian-api"
          EXCLUDE: "/dist/, /node_modules/, *.env, rebuild_app.sh, watcher.sh"
          SCRIPT_AFTER: |
            cd /var/www/petguardian-api &&
            npm install &&
            npm run build &&
            pm2 restart pet-guardian_api        
